# Generated by Django 5.1.5 on 2025-01-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ustoz',
            old_name='nom',
            new_name='ism',
        ),
    ]
