# Generated by Django 5.1.5 on 2025-01-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_nom_ustoz_ism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ustoz',
            old_name='ism',
            new_name='nom',
        ),
    ]
